export const languagesFalse: any = {
    es: {
        who: "Quienes somos",
        solutions: "Soluciones",
        dimensional: "Control Dimensional",
        engineering: "Ingeniería inversa",
        print: "Impresión 3D",
        subs: "Subvenciones",
        desing: "- Diseño y desarrollo: MFi, S.L.",
        terms: "Términos y condiciones",
        conditions: "Condiciones de uso",
        privacy: "Privacidad",
        certs_s: "Contacta con nosotros",
        name: "Nombre",
        surnames: "Apellidos",
        email: "Correo electrónico",
        msg: "Mensaje",
        company: "Empresa",
        phone: "Teléfono",
        contact_us: "Contactar",
        certs: "Política y certificados",
        EN: "EN",
        ES: "ES",
        END: "END"
    },
    en: {
        who: "About us",
        solutions: "Solutions",
        dimensional: "Dimensional Control",
        engineering: "Reverse engineering",
        print: "Print 3D",
        subs: "Subventions",
        desing: "- Design&Development: MFi, S.L.",
        terms: "Terms & Conditions",
        conditions: "User conditions",
        privacy: "Privacy policy",
        contact_us_s: "Contact us",
        name: "Name",
        surnames: "Surnames",
        email: "E-mail",
        msg: "Message",
        company: "Company",
        phone: "Phone",
        contact_us: "Contact",
        certs: "Politics and certificates",
        EN: "EN",
        ES: "ES",
        END: "NDT"
    }
};